# 특정 R 버전이 포함된 Rocker 기반 이미지 선택
FROM rocker/r-ver:latest

RUN R -e "install.packages(c('shiny'))"

# 애플리케이션 복사
COPY app.R /root/app.R

# 기본 포트 노출
EXPOSE 3838

# 애플리케이션 실행 명령
CMD ["R", "-e", "shiny::runApp('/root/app.R', port=3838, host='0.0.0.0')"]