name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_SECRET }}

    - name: Build and push Docker image with shiny server
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/my-shiny-app:latest

    - name: Build and push Docker image with r-base
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile_rbase
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/my-shiny-app-rbase:latest